### ISSUE TITLE
PTB

### ISSUE THREAD

**Issue by vladislavivanistsev** [tblite/tblite#182]
Is it possible to add PTB to TBLITE?

It is already in xTB 6.7.0 – which is not yet updated in conda-forge – and it runs in TBLITE form.

**Comment by awvwgk** [comment]
Maybe Marcel @marcelmbn can comment on this. As far as I know, PTB is only planned to be implemented in `xtb`.

**Comment by marcelmbn** [comment]
PTB was fully implemented into `xtb` in PR https://github.com/grimme-lab/xtb/pull/963.
While it depends on the `tblite` library, we are currently not planning to implement it into `tblite` itself since PTB does not fully match to the first methods implemented (GFN1/2-xTB) as it does not provide energy and gradient.
Also, it's not a self-consistent (like GFNn -xTB) but more a "procedure-like" approach.

If it should be of increasing interest, we can still think about implementing it. 
Regardless, we are still try to bring `xtb-6.7.0` on `conda-forge` as well (which would solve your request already if I understood you correctly).

**Comment by awvwgk** [comment]
Closing this as not planned for now. If there is more interest in having PTB supported with tblite we can revisit this issue.
