### ISSUE TITLE
Compilation fails on Windows-mingw64

### ISSUE THREAD

**Issue by zoziha** [tblite/tblite#31]
I came from [this link](https://github.com/fortran-lang/fpm/pull/676#pullrequestreview-965457802), just out of curiosity, I used mingw64-gfortran to compile `tblite` on windows and found an unexpected error, I am not sure if it is a bug of mingw64-gfortran, but it can be done by replacing the `setenv` routine with `putenv` and solved ([see my code](https://github.com/zoziha/tblite/commit/16dc4a34d35cbf2124c1b2132174198300ec3d72)), the code becomes less, and it seems to be able to compile on windows-ifort and wsl2-gfortran (not very sure)?
```sh
>> fpm build
...
main.f90                               done.
tblite.exe                             failed.
[ 100%]Compiling...
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\gfortran_232594290C1E0524\tblite\libtblite.a(src_tblite_os.F90.o): in function `__tblite_os_MOD_setenv':C:\Users\zoziha\com.zoziha\fortran\tmp\tblite/./src/tblite/os.F90:69: undefined reference to `setenv'     
collect2.exe: error: ld returned 1 exit status
<ERROR> Compilation failed for object " tblite.exe "
<ERROR>stopping due to failed compilation
STOP 1
```

I'm not familiar with `xblite`, probably `xblite` is not intended to support windows-gfortran, if so, please ignore this issue.

**Comment by awvwgk** [comment]
Thanks for raising this issue, supporting Windows is certainly on-scope for this project, however it has been a while since I compiled it using GCC/MinGW. Unfortunately, I'm currently not running CI on Windows to guarantee things keep working. I'll add setting up a GCC/MinGW workflow to my TODO list ;).

I'm happy to include your patch if it fixes the Windows compilation.
